name: CI
on:
  pull_request:
    branches: ['*']

jobs:
  commits:
    name: Check commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: No merge commit
        uses: NexusPHP/no-merge-commits@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: No fixup commit
        uses: 13rac1/block-fixup-merge-action@v2.0.0

  style:
    name: Check code style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      
  test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test